/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mantenimiento;

import javax.swing.JOptionPane;

/**
 *
 * @author miguel
 */
public class Automovil extends javax.swing.JFrame {

     public  int intKilometrajeActual1;//declaramos variable donde vamos a guardar el kilometraje actual de un vehiculo
     public String StringMarca;//en esta variable guardaremos la marca del vehiculo que le usuario ingresara
     public int Modelo;// en esta variable guardaremos el modelo del vehiculo que el usuario ingresara
     public static String mjsNumero="Solo es posible ingresar numeros en esta casilla";//creamos una variable para un mensaje que se utilizara mas adelante
     /**  
     * Creates new form Automovil
     */    
   
    public Automovil() {
        initComponents();
         this.setLocation(350,000);
         //añadimos los botones de radio al grupo de botones para que solo se pueda escojer una sola opcion
         intOpcCarro.add(LlantaPrevencion); 
         intOpcCarro.add(LlantasObligatorio);
         intOpcCarro.add(Frenos);
         intOpcCarro.add(Reparacion);
         intOpcCarro.add(CambioAceite);
         intOpcCarro.add(Filtro);
         intOpcCarro.add(Combustible);

    }

    public static String  getmjsNumero()//creamos el metodo get de la variable string que utilizaremos despues
    {
                 return mjsNumero;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    //init
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try {
            intOpcCarro =(javax.swing.ButtonGroup)java.beans.Beans.instantiate(getClass().getClassLoader(), "mantenimiento.Automovil_intOpcCarro");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        jButton1 = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LlantaPrevencion = new javax.swing.JRadioButton();
        LlantasObligatorio = new javax.swing.JRadioButton();
        Frenos = new javax.swing.JRadioButton();
        Reparacion = new javax.swing.JRadioButton();
        CambioAceite = new javax.swing.JRadioButton();
        Filtro = new javax.swing.JRadioButton();
        Combustible = new javax.swing.JRadioButton();
        Confirmar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        intMarca = new javax.swing.JTextField();
        intModelo = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        kilometrajeactual = new javax.swing.JFormattedTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setToolTipText("");
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setDoubleBuffered(false);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Automovil");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Ingrese marca de su automovil");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Ingrese modelo de su automovil");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Escoja opcion de la tarea que desea realizar");

        LlantaPrevencion.setText("Consultar cuando es necesario cambiar llantas a manera de prevencion");

        LlantasObligatorio.setBackground(new java.awt.Color(255, 255, 255));
        LlantasObligatorio.setText("Consultar cuando es obligatorio cambiar llantas");

        Frenos.setBackground(new java.awt.Color(255, 255, 255));
        Frenos.setText("Consultar cuando es obligatorio cambiar el liquido de frenos");

        Reparacion.setBackground(new java.awt.Color(255, 255, 255));
        Reparacion.setText("Consultar cuando es obligatorio hacer reparacion del motor");

        CambioAceite.setBackground(new java.awt.Color(255, 255, 255));
        CambioAceite.setText("Consultar cuando es necesario cambiar el aceite");

        Filtro.setBackground(new java.awt.Color(255, 255, 255));
        Filtro.setText("Consultar cuando es necesario cambiar el filtro de aceite");

        Combustible.setBackground(new java.awt.Color(255, 255, 255));
        Combustible.setText("Consultar cuanto combustible contiene en su automovil ");

        Confirmar.setText("Confirmar");
        Confirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("ingrese el kilometraje actual");

        intMarca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                intMarcaFocusLost(evt);
            }
        });

        try {
            intModelo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        intModelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                intModeloFocusLost(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mantenimiento/bmw.jpg"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("ejemplo: BMW");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("ejemplo:1993");

        kilometrajeactual.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        kilometrajeactual.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                kilometrajeactualFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(238, 238, 238)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(298, 298, 298)
                                .addComponent(Confirmar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel3))
                                            .addComponent(jLabel4))
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(intMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(intModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kilometrajeactual, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(144, 144, 144))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Reparacion)
                                    .addComponent(CambioAceite)
                                    .addComponent(Filtro)
                                    .addComponent(Combustible)
                                    .addComponent(LlantaPrevencion)
                                    .addComponent(LlantasObligatorio)
                                    .addComponent(Frenos))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(intModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(kilometrajeactual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LlantaPrevencion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LlantasObligatorio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Frenos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(Reparacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CambioAceite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Filtro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Combustible))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Confirmar)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed

        if(LlantaPrevencion.isSelected())//con el if ponemos una condicion si LlantaPrevencion es seleccionado se ejecutara lo que este dentro de los parentesis 
        {
            java.awt.EventQueue.invokeLater(new Runnable() 
            {
                public void run() 
                {
                    setVisible(false);//se desactiva el modo de visibilidad de este formulario cuando llegue el otro formulario
                    //lo siguiente se realiza para crear una instancia de la clase del formulario que vamos a llamar con un nombre especifico y no dejarla crear automaticamente ya que es necesario utilizarla al llamar el metodo get que utilizaremos
                    Llanta_prevencion aa =  new Llanta_prevencion();// creamos una instancia del formulario al que vamos a llamar aa
                    aa.getinKilometrajeActual(intKilometrajeActual1);//llamamos un metodo que fue creado en el formulario siguiente, este metodo recive un argumento que en este caso es la variable que guarda el texto de kilometrajeactual 
                    //los siguientes metodos realizan la misma tarea que  getinKilometrajeActual solo cambian las varibales que guardan
                    aa.getmarca(StringMarca);
                    aa.getmodelo(Modelo);
                    aa.setVisible(true);//el nuevo formulario se activa para q se vea

                }
            });
        }//cada if hace lo mismo solo que selecciona cada boton del formulario y direcciona a diferentes formularios dependiendo del boton seleccionado 
         else{
            if(LlantasObligatorio.isSelected())
            {
             java.awt.EventQueue.invokeLater(new Runnable() 
             {
                 public void run() 
                    {
                     setVisible(false); 
                     Llanta_obligatorio bb =  new Llanta_obligatorio();
                     bb.getinKilometrajeActual(intKilometrajeActual1);
                     bb.getmarca(StringMarca);
                     bb.getmodelo(Modelo);
                     bb.setVisible(true);
                    }
             });
            }else{if(Frenos.isSelected())
                    {
                     java.awt.EventQueue.invokeLater(new Runnable() 
                     {
                     public void run() 
                     {
                      setVisible(false); 
                      Cambio_liquido_frenos cc =  new Cambio_liquido_frenos();
                      cc.getinKilometrajeActual(intKilometrajeActual1);
                      cc.getmarca(StringMarca);
                      cc.getmodelo(Modelo);
                      cc.setVisible(true);   
                     }
                     });

                    }else{if(Reparacion.isSelected())
                            {
                             java.awt.EventQueue.invokeLater(new Runnable() 
                             {
                             public void run() 
                             {
                             setVisible(false); 
                             Reparacion_motor dd =  new Reparacion_motor();
                             dd.getinKilometrajeActual(intKilometrajeActual1);
                             dd.getmarca(StringMarca);
                             dd.getmodelo(Modelo);
                             dd.setVisible(true);   
                             }
                             });
                             }else{if(CambioAceite.isSelected())
                                      {
                                       java.awt.EventQueue.invokeLater(new Runnable() 
                                       {
                                       public void run() 
                                       {
                                           setVisible(false); 
                                            cambio_aceite ee =  new cambio_aceite();
                                            ee.getinKilometrajeActual(intKilometrajeActual1);
                                            ee.getmarca(StringMarca);
                                            ee.getmodelo(Modelo);
                                            ee.setVisible(true);  
                                        }
                                        });
                                      }else{if(Filtro.isSelected())
                                               {
                                                java.awt.EventQueue.invokeLater(new Runnable() 
                                                {
                                                public void run() 
                                                {
                                                    setVisible(false); 
                                                    filtro_aceite ff =  new filtro_aceite();
                                                    ff.getinKilometrajeActual(intKilometrajeActual1);
                                                    ff.getmarca(StringMarca);
                                                    ff.getmodelo(Modelo);
                                                    ff.setVisible(true);  
                                                }
                                                });
                                                }else{if(Combustible.isSelected())
                                                        {                     
                                                         java.awt.EventQueue.invokeLater(new Runnable() 
                                                         {
                                                         public void run() 
                                                         {
                                                            setVisible(false); 
                                                            combustible gg =  new combustible();
                                                            gg.getmarca(StringMarca);
                                                            gg.getmodelo(Modelo);
                                                            gg.setVisible(true);  
                                                         }
                                                         });
                                                         }else{
                                                               JOptionPane.showMessageDialog(this, TipoVehiculo.getmensaje());//imprime el srtring del mensaje creado anteriormente
                                                              }
                                                     }
                                            }
                                }
                          }
                }
             }
    }//GEN-LAST:event_ConfirmarActionPerformed

    private void intMarcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_intMarcaFocusLost
         StringMarca=intMarca.getText();//guardamos lo que el usuario ingrese en la variable StringMarca 
    }//GEN-LAST:event_intMarcaFocusLost

    private void intModeloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_intModeloFocusLost
         //el siguiente codigo se genera dentro de el evento focus lost para no perder la informacion que se captura en la caja de texto intModelo
         //creamos las siguientes variables para guardar mensajes en especifico que seran usados en la mayoria de los formularos
         String mjsmodelo="El año / modelo no puede ser mayor a 2014 o menor a 1922";
         String mjsdigitosmodelo="El año / modelo debe contener 4 digitos"; 
        //se usa la siguiente excepcion para asegurarnos que el usuario ingrese 4 digitos en la caja de texto
        try
        {
         Modelo=Integer.parseInt(intModelo.getText());//se transforma el texto que ingreso el usuario en entero y se guarda en la variable Modelo
         if((Modelo>2014)||(Modelo<1922))//1922 es el año en que se empezó a desarrollar la primera industria de automoviles en masa con la marca austin 7
         {
          JOptionPane.showMessageDialog(this,mjsmodelo);
         }
        }catch(Exception a)//si no se cumple con la condicion anterior se generara una excepcion a que ejecutara lo contenido en los parentesis
        {
         JOptionPane.showMessageDialog(this,mjsdigitosmodelo);//se imprime mensansaje que contiene la variable mjsdigitosmodelo
        } 
    }//GEN-LAST:event_intModeloFocusLost

    private void kilometrajeactualFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kilometrajeactualFocusLost

        try
        { 
        intKilometrajeActual1=Integer.parseInt(kilometrajeactual.getText());// guardamos lo capturado en al caja de texto en la variable intKilometrajeActual1
        }catch(Exception e)
        {
         JOptionPane.showMessageDialog(this, mjsNumero);
        }
    }//GEN-LAST:event_kilometrajeactualFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Automovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Automovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Automovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Automovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Automovil().setVisible(true);
                TipoVehiculo u= new TipoVehiculo ();
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CambioAceite;
    private javax.swing.JRadioButton Combustible;
    private javax.swing.JButton Confirmar;
    private javax.swing.JRadioButton Filtro;
    private javax.swing.JRadioButton Frenos;
    private javax.swing.JRadioButton LlantaPrevencion;
    private javax.swing.JRadioButton LlantasObligatorio;
    private javax.swing.JRadioButton Reparacion;
    private javax.swing.JTextField intMarca;
    private javax.swing.JFormattedTextField intModelo;
    private javax.swing.ButtonGroup intOpcCarro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JFormattedTextField kilometrajeactual;
    // End of variables declaration//GEN-END:variables
}
