/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mantenimiento;

import javax.swing.JOptionPane;

/**
 *
 * @author miguel
 */
public class cambio_aceite extends javax.swing.JFrame {

    /**
     * Creates new form cambio_aceite
     */
    public cambio_aceite() {
        initComponents();
        this.setLocation(350,000);
        //a continuacion se añade cada radio button a un group button para que 
        //solo sea posible escojer una de estas dos opciones
        intOpcAceite.add(Monogrado);
        intOpcAceite.add(Multigrado);
    }
    int intKilometrajeActual;//declaramos la variable donde se guardara el kilometraje que el usuario ingreso en le formulario anterior
    String StringMarca;
    int intModelo;
    int intKilometrajeCambioDeAceite;
    int intCambioAceite;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        intOpcAceite = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        cambio_aceite = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resultado = new javax.swing.JTextArea();
        Monogrado = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        Multigrado = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Consultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Cambio De Aceite");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Ingrese el kilometraje en el que se realizo el ultimo cambio de aceite");

        aceptar.setText("Aceptar");
        aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        cambio_aceite.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        cambio_aceite.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cambio_aceiteFocusLost(evt);
            }
        });

        Resultado.setEditable(false);
        Resultado.setBackground(new java.awt.Color(153, 204, 255));
        Resultado.setColumns(20);
        Resultado.setRows(5);
        jScrollPane1.setViewportView(Resultado);

        Monogrado.setText("Tipo Monogrado");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Selecione uno de los siguientes tipos de aceite y a continuacion clik en aceptar");

        Multigrado.setText("Tipo Multigrado");

        jLabel5.setText("Click en consultar nuevamente para realizar una nueva consulta");

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\universidad\\semestre VI\\ingenieria de software\\Empresa M&D Software\\software\\java\\imagenes apra los formularios\\aceite completo.jpg")); // NOI18N
        jLabel6.setText("jLabel6");

        Consultar.setText("Consultar nuevamente");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addComponent(Multigrado))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(aceptar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Monogrado, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Consultar)
                        .addGap(176, 176, 176))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cambio_aceite, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(342, 342, 342))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(166, 166, 166))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(315, 315, 315))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(cambio_aceite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Monogrado)
                    .addComponent(Multigrado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aceptar)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Consultar))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        intCambioAceite=intKilometrajeActual-intKilometrajeCambioDeAceite;
        
        if(Monogrado.isSelected())
        {
          if((intCambioAceite==5000)||(intCambioAceite>5000))//la condicion es usando los 5000 kilometros del limite
            {
              Resultado.setText("MARCA: "+StringMarca+"\n\n"+"MODELO:  "+intModelo+"\n\n"+"El vehiculo ha redorrido "+ intCambioAceite+" kilometros desde\n el ultimo cambio.\n\nEs recomendable realizar un cambio de aceite\nen este momento, ya que se ha recorrido mas\nde 5000 kilometros");                                  
             }else
                  {
                    Resultado.setText("MARCA:  "+StringMarca+"\n\n"+"MODELO:  "+intModelo+"\n\n"+"El vehiculo ha recorrido "+intCambioAceite+" kilometros desde\nel ultimo cambio.\n\n"+"No es necesario realizar el cambio en este momento,\nrecuerde que es recomendable cambiar aceite\ndespues de recorrer 5000 kilometros");
                  }
        }// cierre del if monogrado
        else{
             if(Multigrado.isSelected())
                {
                 if((intCambioAceite==10000)||(intCambioAceite>10000))//la condicion es usando los 10000 kilometros del limite
                     {
                        Resultado.setText("MARCA: "+StringMarca+"\n\n"+"MODELO:  "+intModelo+"\n\n"+"El vehiculo ha redorrido "+ intCambioAceite+" kilometros desde\n el ultimo cambio.\n\nEs recomendable realizar un cambio de aceite\nen este momento, ya que se ha recorrido mas\nde 10000 kilometros");                                  
                     }else
                        {
                          Resultado.setText("MARCA:  "+StringMarca+"\n\n"+"MODELO:  "+intModelo+"\n\n"+"El vehiculo ha recorrido "+intCambioAceite+" kilometros desde\nel ultimo cambio.\n\n"+"No es necesario realizar el cambio en este momento,\nrecuerde que es recomendable cambiar aceite\ndespues de recorrer 10000 kilometros");
                        }
                }//cierre if multigrado
                else{
                     JOptionPane.showMessageDialog(this, TipoVehiculo.getmensaje());//imprime el srtring del mensaje creado anteriormente
                    }
            }
    }//GEN-LAST:event_aceptarActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        //al dar click en consultar automaticamente se devuelve al menu principal apra iniciar una nueva consulta
        setVisible(false);
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoVehiculo().setVisible(true);
            }
        });
    }//GEN-LAST:event_ConsultarActionPerformed

    private void cambio_aceiteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cambio_aceiteFocusLost
       try{ 
          intKilometrajeCambioDeAceite=Integer.parseInt(this.cambio_aceite.getText());
         }catch(Exception a)
         {
         JOptionPane.showMessageDialog(this, Automovil.getmjsNumero());
         } 
    }//GEN-LAST:event_cambio_aceiteFocusLost

    /**
     * @param args the command line arguments
     */
    
    //A continuacion crearemos los metodos cada uno con un argumento el cual nos permitira obtener el valor que el 
    //usuario ingreso en el formulario Automovil
    public void getinKilometrajeActual (int kilometraje)
    {
        intKilometrajeActual=kilometraje;
         
    }
    public void getmarca(String marca)
    {
       StringMarca=marca;
    }
    public void getmodelo(int modelo)
    {
       intModelo=modelo;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cambio_aceite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cambio_aceite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cambio_aceite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cambio_aceite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cambio_aceite().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Consultar;
    private javax.swing.JRadioButton Monogrado;
    private javax.swing.JRadioButton Multigrado;
    private javax.swing.JTextArea Resultado;
    private javax.swing.JButton aceptar;
    private javax.swing.JFormattedTextField cambio_aceite;
    private javax.swing.ButtonGroup intOpcAceite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
