/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mantenimiento;

import javax.swing.JOptionPane;

/**
 *
 * @author miguel
 */
public class Camioneta extends javax.swing.JFrame {

    /**
     * Creates new form Camioneta
     */
     public  int intKilometrajeActual;//declaramos variable donde vamos a guardar el kilometraje actual de in vehiculo
     public String StringMarca;//en esta variable guardaremos la marca del vehiculo que le usuario ingresara
     public int intModelo;
     public static String mjsNumero;
     public Camioneta() {
        initComponents();
         this.setLocation(350,000);
         intOpcCamioneta.add(LlantaPrevencion);//añadimos el boton 1 que es cambiar llantas a manera de prevencion al prupo de botones para que solo se pueda escojer uno solo 
         intOpcCamioneta.add(LlantasObligatorio);
         intOpcCamioneta.add(Frenos);
         intOpcCamioneta.add(Reparacion);
         intOpcCamioneta.add(CambioAceite);
         intOpcCamioneta.add(Filtro);
         intOpcCamioneta.add(Combustible);
    }
    public static String  getmjsNumero()//creamos el metodo get de la variable string que utilizamos anteriormente
    {
                 return mjsNumero;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        intOpcCamioneta = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        marca = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        modelo = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        kilometrajeactual = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        LlantaPrevencion = new javax.swing.JRadioButton();
        LlantasObligatorio = new javax.swing.JRadioButton();
        Frenos = new javax.swing.JRadioButton();
        Reparacion = new javax.swing.JRadioButton();
        CambioAceite = new javax.swing.JRadioButton();
        Filtro = new javax.swing.JRadioButton();
        Combustible = new javax.swing.JRadioButton();
        aceptar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Camioneta");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Ingrese marca de su camioneta");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ejemplo: toyota");

        marca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                marcaFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Ingrese modelo de su camioneta");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("ejemplo:1989");

        try {
            modelo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        modelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                modeloFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Ingrese el kilometraje actual");

        kilometrajeactual.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        kilometrajeactual.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                kilometrajeactualFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Escoja opcion de la tarea que desea realizar");

        LlantaPrevencion.setText("Consultar cuando es necesario cambiar llantas a manera de prevencion");

        LlantasObligatorio.setText("Consultar cuando es obligatorio cambiar llantas");

        Frenos.setText("Consultar cuando es obligatorio cambiar el liquido de frenos");

        Reparacion.setText("Consultar cuando es obligatorio hacer reparacion del motor");

        CambioAceite.setText("Consultar cuando es necesario cambiar el aceite");

        Filtro.setText("Consultar cuando es necesario cambiar el filtro de aceite");

        Combustible.setText("Consultar cuanto combustible contiene en su camioneta");

        aceptar.setText("Aceptar");
        aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mantenimiento/2012-Toyota-Fortuner-forcarscoop-84490001.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kilometrajeactual, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Reparacion)
                    .addComponent(CambioAceite)
                    .addComponent(Frenos)
                    .addComponent(LlantasObligatorio)
                    .addComponent(LlantaPrevencion)
                    .addComponent(Filtro)
                    .addComponent(Combustible))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addComponent(aceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel7)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(33, 33, 33)
                        .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(kilometrajeactual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(aceptar)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LlantaPrevencion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LlantasObligatorio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Frenos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Reparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CambioAceite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Filtro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Combustible)
                        .addGap(105, 105, 105))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        if(LlantaPrevencion.isSelected())
        {
            java.awt.EventQueue.invokeLater(new Runnable() 
            {
                public void run() 
                {
                    setVisible(false);//se secativa el modo de visibilidad de este formulario cuando lelgue el otro formulario
                    //lo siguiente se realiza para crear una instancia de la clase del formulario que vamos a llamar con un nombre especifico y no dejarla crear automaticamente ya que es necesario utilizarla al llamar el metodo get que utilizaremos
                    Llanta_prevencion aa =  new Llanta_prevencion();// creamos una instancia del formulario al que vamos a llamar
                    aa.getinKilometrajeActual(intKilometrajeActual);//llamamos un metodo que fue creado en el formulario siguiente, este metodo recive un argumento que en este caso es la variable que guarda el texto de kilometrajeactual 
                    aa.getmarca(StringMarca);
                    aa.getmodelo(intModelo);
                    aa.setVisible(true);//el nuevo formulario se activa para q se vea

                }
            });
        }else{
            if(LlantasObligatorio.isSelected())
            {
             java.awt.EventQueue.invokeLater(new Runnable() 
             {
                 public void run() 
                    {
                     setVisible(false); 
                     Llanta_obligatorio bb =  new Llanta_obligatorio();
                     bb.getinKilometrajeActual(intKilometrajeActual);
                     bb.getmarca(StringMarca);
                     bb.getmodelo(intModelo);
                     bb.setVisible(true);
                    }
             });
            }else{if(Frenos.isSelected())
                    {
                     java.awt.EventQueue.invokeLater(new Runnable() 
                     {
                     public void run() 
                     {
                      setVisible(false); 
                      Cambio_liquido_frenos cc =  new Cambio_liquido_frenos();
                      cc.getinKilometrajeActual(intKilometrajeActual);
                      cc.getmarca(StringMarca);
                      cc.getmodelo(intModelo);
                      cc.setVisible(true);   
                     }
                     });

                    }else{if(Reparacion.isSelected())
                            {
                             java.awt.EventQueue.invokeLater(new Runnable() 
                             {
                             public void run() 
                             {
                             setVisible(false); 
                             Reparacion_motor dd =  new Reparacion_motor();
                             dd.getinKilometrajeActual(intKilometrajeActual);
                             dd.getmarca(StringMarca);
                             dd.getmodelo(intModelo);
                             dd.setVisible(true);   
                             }
                             });
                             }else{if(CambioAceite.isSelected())
                                      {
                                       java.awt.EventQueue.invokeLater(new Runnable() 
                                       {
                                       public void run() 
                                       {
                                           setVisible(false); 
                                            cambio_aceite ee =  new cambio_aceite();
                                            ee.getinKilometrajeActual(intKilometrajeActual);
                                            ee.getmarca(StringMarca);
                                            ee.getmodelo(intModelo);
                                            ee.setVisible(true);  
                                        }
                                        });
                                      }else{if(Filtro.isSelected())
                                               {
                                                java.awt.EventQueue.invokeLater(new Runnable() 
                                                {
                                                public void run() 
                                                {
                                                    setVisible(false); 
                                                    filtro_aceite ff =  new filtro_aceite();
                                                    ff.getinKilometrajeActual(intKilometrajeActual);
                                                    ff.getmarca(StringMarca);
                                                    ff.getmodelo(intModelo);
                                                    ff.setVisible(true);  
                                                }
                                                });
                                                }else{if(Combustible.isSelected())
                                                        {                     
                                                         java.awt.EventQueue.invokeLater(new Runnable() 
                                                         {
                                                         public void run() 
                                                         {
                                                             setVisible(false); 
                                                            combustible_camioneta gg =  new combustible_camioneta();
                                                            gg.getmarca(StringMarca);
                                                            gg.getmodelo(intModelo);
                                                            gg.setVisible(true);  
                                                         }
                                                         });
                                                         }else{
                                                               JOptionPane.showMessageDialog(this, TipoVehiculo.getmensaje());//imprime el srtring del mensaje creado anteriormente
                                                              }
                                                     }
                                            }
                                }
                          }
                }
             }
    // TODO add your handling code here:
    }//GEN-LAST:event_aceptarActionPerformed

    private void modeloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_modeloFocusLost
        String mjsmodelo="El año / modelo no puede ser mayor a 2014 ni menor a 1922";
        String mjsdigitosmodelo="El año / modelo debe contener 4 digitos"; 
        //se usa la siguiente excepcion para asegurarnos que el usuario ingrese 4 digitos en la caja de texto
        try
        {
         intModelo=Integer.parseInt(modelo.getText());//se transforma el texto que ingreso el usuario en entero y se guarda en la variable Modelo
         if((intModelo>2014)||(intModelo<1922))//1922 es el año en que se empezó a desarrollar la primera industria de automoviles en masa con la marca austin 7
         {
          JOptionPane.showMessageDialog(this,mjsmodelo);//se imprime mensansaje que contiene la variable mjsmodelo
         }
        }catch(Exception a)//si las lineas de arriba no se cumplen se realiza la siguiente excepcion
        {
        JOptionPane.showMessageDialog(this,mjsdigitosmodelo);//se imprime mensansaje que contiene la variable mjsdigitosmodelo
        }
    }//GEN-LAST:event_modeloFocusLost

    private void marcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_marcaFocusLost
         StringMarca=marca.getText();
    }//GEN-LAST:event_marcaFocusLost

    private void kilometrajeactualFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kilometrajeactualFocusLost
       mjsNumero="Solo es posible ingresar numeros en esta casilla";
        try
        { 
        intKilometrajeActual=Integer.parseInt(kilometrajeactual.getText());// TODO add your handling code here:
        }catch(Exception e)
        {
         JOptionPane.showMessageDialog(this, mjsNumero);
        }
    }//GEN-LAST:event_kilometrajeactualFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Camioneta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Camioneta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Camioneta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Camioneta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Camioneta().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CambioAceite;
    private javax.swing.JRadioButton Combustible;
    private javax.swing.JRadioButton Filtro;
    private javax.swing.JRadioButton Frenos;
    private javax.swing.JRadioButton LlantaPrevencion;
    private javax.swing.JRadioButton LlantasObligatorio;
    private javax.swing.JRadioButton Reparacion;
    private javax.swing.JButton aceptar;
    private javax.swing.ButtonGroup intOpcCamioneta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JFormattedTextField kilometrajeactual;
    private javax.swing.JFormattedTextField marca;
    private javax.swing.JFormattedTextField modelo;
    // End of variables declaration//GEN-END:variables
}
