/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mantenimiento;
import java.text.DecimalFormat;//importamos esta clase para restringir el numero de decimales que apareceran en la pantalla al imprimir un mensaje
import javax.swing.JOptionPane;
/**
 *
 * @author miguel
 */
public class combustible_camioneta extends javax.swing.JFrame {

    /**
     * Creates new form combustible_camioneta
     */
     public String StringMarca;//en esta variable guardaremos la marca del vehiculo que le usuario ingresara
     public int intModelo;
     //en las siguientes variables guardamos el valor y la cantidad de gasolina, las definimos como double ya que nos dara una mayor exactitud cunado veamos cuantos galones tiene un vehiculo
     double doubleGasolina;
     double doubleGalones;
    public combustible_camioneta() {
        initComponents();
        this.setLocation(350,000);
        //se asigna cada radio button a un group botton en este caso se llama
        //intOpcGas
        intOpcGas.add(Extra);
        intOpcGas.add(Acpm);
        intOpcGas.add(Corriente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        intOpcGas = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        gasolina = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        Corriente = new javax.swing.JRadioButton();
        Acpm = new javax.swing.JRadioButton();
        Extra = new javax.swing.JRadioButton();
        Aceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rendimiento = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        consultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Combustible");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Ingrese la cantidad de dinero  en pesos sin puntos ni comas");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText(" que gastó en gasolina para su camioneta");

        gasolina.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        gasolina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gasolinaActionPerformed(evt);
            }
        });
        gasolina.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                gasolinaFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Escoja el tipo de gasolina que utilizó para su vehiculo y a continuación click en aceptar");

        Corriente.setText("Corriente");

        Acpm.setText("Acpm");

        Extra.setText("Extra");

        Aceptar.setText("Aceptar");
        Aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        resultado.setEditable(false);
        resultado.setBackground(new java.awt.Color(153, 204, 255));
        resultado.setColumns(20);
        resultado.setRows(5);
        jScrollPane1.setViewportView(resultado);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mantenimiento/gasolina terminada.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel5.setText("Click en Rendimiento para saber cuantos kilometros recorrera");

        jLabel7.setText("el vehiculo con esta cantidad de galones.");

        rendimiento.setText("Rendimiento");
        rendimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rendimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rendimientoActionPerformed(evt);
            }
        });

        jLabel8.setText("Click en consultar para realizar una nueva consulta");

        consultar.setText("Consultar");
        consultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(337, 337, 337))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Corriente)
                                .addGap(311, 311, 311)
                                .addComponent(Acpm, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                                .addComponent(Extra, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(gasolina, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(327, 327, 327))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Aceptar)
                                .addGap(361, 361, 361))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(rendimiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(consultar)
                .addGap(174, 174, 174))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addComponent(gasolina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Corriente)
                    .addComponent(Acpm)
                    .addComponent(Extra))
                .addGap(50, 50, 50)
                .addComponent(Aceptar)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rendimiento)
                            .addComponent(consultar))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(81, 81, 81))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gasolinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gasolinaActionPerformed
        try{ 
          doubleGasolina=Integer.parseInt(this.gasolina.getText());
         }catch(Exception a)
         {
         JOptionPane.showMessageDialog(this, Automovil.getmjsNumero());
         }// TODO add your handling code here:
    }//GEN-LAST:event_gasolinaActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        if(Corriente.isSelected())
        {
            doubleGalones=doubleGasolina/8751;//8751 es el precio actual de la gasolina corriente en bogota, dividimos el nuemro ingresado por el usuario enter el valor y tenemos la cantidad de galoes que ingresaron, luego guardamos el resultado en intGalones
            DecimalFormat df = new DecimalFormat("0.000");// creamos una variable de la clase DecimalFormat para restringir la catidad de decimales que deseamos imprmir en pantalla, en este caso seran solo tres decimales
            resultado.setText("MARCA: "+StringMarca+"\n\n"+"MODELO:  "+intModelo+"\n\n"+"La cantidad de gasolina que ingreso en su vehiculo\nes: "+df.format(doubleGalones)+" galones de gasolina");
            //cuaado utilizamos esta linea de codigo--->df.format(doubleGalones); estamos asigandole la restriccion de decimales a la variable doubleGalones para que no imprima todos los decimaes completos
        }else
        {
            if(Acpm.isSelected())
            {
                doubleGalones=doubleGasolina/8472;//8751 es el precio actual de la gasolina corriente en bogota, dividimos el nuemro ingresado por el usuario enter el valor y tenemos la cantidad de galoes que ingresaron, luego guardamos el resultado en intGalones
                DecimalFormat df = new DecimalFormat("0.000");// creamos una variable de la clase DecimalFormat para restringir la catidad de decimales que deseamos imprmir en pantalla, en este caso seran solo tres decimales
                resultado.setText("MARCA: "+StringMarca+"\n\n"+"MODELO:  "+intModelo+"\n\n"+"La cantidad de gasolina que ingreso en su vehiculo\nes: "+df.format(doubleGalones)+" galones de gasolina");
                //cuaado utilizamos esta linea de codigo--->df.format(doubleGalones); estamos asigandole la restriccion de decimales a la variable doubleGalones para que no imprima todos los decimaes completos
            }else
            {
                if(Extra.isSelected())
                {
                    doubleGalones=doubleGasolina/10391;//8751 es el precio actual de la gasolina corriente en bogota, dividimos el nuemro ingresado por el usuario enter el valor y tenemos la cantidad de galoes que ingresaron, luego guardamos el resultado en intGalones
                    DecimalFormat df = new DecimalFormat("0.000");// creamos una variable de la clase DecimalFormat para restringir la catidad de decimales que deseamos imprmir en pantalla, en este caso seran solo tres decimales
                    resultado.setText("MARCA: "+StringMarca+"\n\n"+"MODELO:  "+intModelo+"\n\n"+"La cantidad de gasolina que ingreso en su vehiculo\nes: "+df.format(doubleGalones)+" galones de gasolina");
                    //cuaado utilizamos esta linea de codigo--->df.format(doubleGalones); estamos asigandole la restriccion de decimales a la variable doubleGalones para que no imprima todos los decimaes completos
                }else
                {
                    JOptionPane.showMessageDialog(this, TipoVehiculo.getmensaje());//imprime el srtring del mensaje creado anteriormente
                }
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_AceptarActionPerformed

    private void rendimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rendimientoActionPerformed
        //ESte boton nos permitira ir al formulario donde nos dara una opcion 
        //para saber el kilometraje recorrido con la cantidad de galones previamente
        //hallada
        //al igual que en el formulario Automovil y camioneta generamos una instancia 
//        en el formulario que vamos a llamar con los metodos requeridos para usar 
//        las variables de un formulario a otro
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 setVisible(false);
                 rendimiento_camioneta rc = new rendimiento_camioneta();
                 rc.getgalones(doubleGalones);
                 rc.getmarca(StringMarca);
                 rc.getmodelo(intModelo);
                 rc.setVisible(true);
            }
        });
    }//GEN-LAST:event_rendimientoActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoVehiculo().setVisible(true);
            }
        });// TODO add your handling code here:
    }//GEN-LAST:event_consultarActionPerformed

    private void gasolinaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gasolinaFocusLost
         String mjsNumero="Solo es posible ingresar numeros en esta casilla";
         try
         { 
          doubleGasolina=Integer.parseInt(this.gasolina.getText());
         }catch(Exception a)
         {
         JOptionPane.showMessageDialog(this, mjsNumero);
         }
    }//GEN-LAST:event_gasolinaFocusLost
    //A continuacion crearemos los metodos cada uno con un argumento el cual nos permitira obtener el valor que el 
    //usuario ingreso en el formulario Automovil
    public void getmarca(String marca)
    {
       StringMarca=marca;
    }
    public void getmodelo(int modelo)
    {
       intModelo=modelo;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(combustible_camioneta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(combustible_camioneta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(combustible_camioneta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(combustible_camioneta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new combustible_camioneta().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JRadioButton Acpm;
    private javax.swing.JRadioButton Corriente;
    private javax.swing.JRadioButton Extra;
    private javax.swing.JButton consultar;
    private javax.swing.JFormattedTextField gasolina;
    private javax.swing.ButtonGroup intOpcGas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rendimiento;
    private javax.swing.JTextArea resultado;
    // End of variables declaration//GEN-END:variables
}
