/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mantenimiento;

import javax.swing.JOptionPane;
import java.text.DecimalFormat;//importamos esta libreria para restringir el numero de decimales que apareceran en la pantalla al imprimir un mensaje

/**
 *
 * @author miguel
 */
public class Galones_Carro extends javax.swing.JFrame {

    /**
     * Creates new form Galones_Carro
     */
    String StringMarca;
    int intModelo;
    double doubleGalones;
    double KilometrajeRendimiento; //en esta variable guardaremos el kilometraje que el automovil recorrera con los galones que tiene el vehiculo
    public Galones_Carro() {
        initComponents();
        this.setLocation(350,000);
        //se asigna cada radio button a un group botton en este caso se llama 
        //opcCilindraje
        OpcCilindraje.add(A);
        OpcCilindraje.add(B);
        OpcCilindraje.add(C);
        OpcCilindraje.add(D);
        OpcCilindraje.add(E);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OpcCilindraje = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        A = new javax.swing.JRadioButton();
        B = new javax.swing.JRadioButton();
        C = new javax.swing.JRadioButton();
        D = new javax.swing.JRadioButton();
        E = new javax.swing.JRadioButton();
        Aceptar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        consultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("RENDIMIENTO DEL COMBUSTIBLE");

        resultado.setEditable(false);
        resultado.setBackground(new java.awt.Color(153, 204, 255));
        resultado.setColumns(20);
        resultado.setRows(5);
        jScrollPane1.setViewportView(resultado);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Seleccione el cilindraje de su automovil de las siguientes opciones y click en aceptar:");

        A.setText("Entre 900 y 1299");

        B.setText("Entre 1300 y 1599");

        C.setText(" Entre 1600 y 1799");

        D.setText("Entre 1800 y 1999");

        E.setText("Entre 2000 y 2500");

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mantenimiento/rendimiento gas completo.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel4.setText("Click en consultar nuevamente para realizar una nueva consulta");

        consultar.setText("Consultar nuevamente");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(B)
                .addGap(198, 198, 198)
                .addComponent(C)
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(D)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(E)
                .addGap(190, 190, 190))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(364, 364, 364)
                                .addComponent(Aceptar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(consultar)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A)
                    .addComponent(B)
                    .addComponent(C))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D)
                    .addComponent(E))
                .addGap(29, 29, 29)
                .addComponent(Aceptar)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(consultar))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        DecimalFormat df = new DecimalFormat("0.000");
        if(A.isSelected())
        {
          KilometrajeRendimiento=45*doubleGalones;
          resultado.setText("MARCA: "+StringMarca+"\n\n"+"MODELO:  "+intModelo+"\n\n"+"El vehiculo con  " +df.format(doubleGalones)+" galones\nrecorrera  "+df.format(KilometrajeRendimiento)+" kilometros\n\n\nNota: Esta distancia puede ser alterada\nsi se mantiene  el vehiculo estacionado\ncon el motor encendido por algun tiempo\no si se sobrepasan los limites de velocidad.");
          //en la impresion anterior usamos df.format(variable) para que esos valores nos muestren en pantalla solo la cantidad decimal deseada
        }else{
            if(B.isSelected())
            {
             KilometrajeRendimiento=42*doubleGalones;
             resultado.setText("MARCA: "+StringMarca+"\n\n"+"MODELO:  "+intModelo+"\n\n"+"El vehiculo con  " +df.format(doubleGalones)+" galones\nrecorrera  "+df.format(KilometrajeRendimiento)+" kilometros\n\n\nNota: Esta distancia puede ser alterada\nsi se mantiene  el vehiculo estacionado\ncon el motor encendido por algun tiempo\no si se sobrepasan los limites de velocidad.");
          //en la impresion anterior usamos df.format(variable) para que esos valores nos muestren en pantalla solo la cantidad decimal deseada
            }else{
                if(C.isSelected())
                    {
                     KilometrajeRendimiento=38*doubleGalones;
                     resultado.setText("MARCA: "+StringMarca+"\n\n"+"MODELO:  "+intModelo+"\n\n"+"El vehiculo con  " +df.format(doubleGalones)+" galones\nrecorrera  "+df.format(KilometrajeRendimiento)+" kilometros\n\n\nNota: Esta distancia puede ser alterada\nsi se mantiene  el vehiculo estacionado\ncon el motor encendido por algun tiempo\no si se sobrepasan los limites de velocidad.");
          //en la impresion anterior usamos df.format(variable) para que esos valores nos muestren en pantalla solo la cantidad decimal deseada

                    }else{
                          if(D.isSelected())
                            {
                             KilometrajeRendimiento=28*doubleGalones;
                             resultado.setText("MARCA: "+StringMarca+"\n\n"+"MODELO:  "+intModelo+"\n\n"+"El vehiculo con  " +df.format(doubleGalones)+" galones\nrecorrera  "+df.format(KilometrajeRendimiento)+" kilometros\n\n\nNota: Esta distancia puede ser alterada\nsi se mantiene  el vehiculo estacionado\ncon el motor encendido por algun tiempo\no si se sobrepasan los limites de velocidad.");
          //en la impresion anterior usamos df.format(variable) para que esos valores nos muestren en pantalla solo la cantidad decimal deseada
                            }else{
                              if(E.isSelected())
                                 {
                                   KilometrajeRendimiento=23*doubleGalones;
                                   resultado.setText("MARCA: "+StringMarca+"\n\n"+"MODELO:  "+intModelo+"\n\n"+"El vehiculo con  " +df.format(doubleGalones)+" galones\nrecorrera  "+df.format(KilometrajeRendimiento)+" kilometros\n\n\nNota: Esta distancia puede ser alterada\nsi se mantiene  el vehiculo estacionado\ncon el motor encendido por algun tiempo\no si se sobrepasan los limites de velocidad.");
          //en la impresion anterior usamos df.format(variable) para que esos valores nos muestren en pantalla solo la cantidad decimal deseada  
                                 }else{
                                      JOptionPane.showMessageDialog(this, TipoVehiculo.getmensaje());//imprime el srtring del mensaje creado anteriormente
                                      }
                                 }
                          }    
                  }
                }
    }//GEN-LAST:event_AceptarActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        setVisible(false);
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoVehiculo().setVisible(true);
            }
        });
    }//GEN-LAST:event_consultarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    //A continuacion crearemos los metodos cada uno con un argumento el cual nos permitira obtener el valor que el 
    //usuario ingreso en el formulario Automovil y combustible
    public void getgalones(double galones) //generamos un metodo para capturar la variable de galones del formulario combustible
    {
       doubleGalones=galones;
    }
    public void getmarca(String marca)
    {
       StringMarca=marca;
    }
    public void getmodelo(int modelo)
    {
       intModelo=modelo;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Galones_Carro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Galones_Carro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Galones_Carro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Galones_Carro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Galones_Carro().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A;
    private javax.swing.JButton Aceptar;
    private javax.swing.JRadioButton B;
    private javax.swing.JRadioButton C;
    private javax.swing.JRadioButton D;
    private javax.swing.JRadioButton E;
    private javax.swing.ButtonGroup OpcCilindraje;
    private javax.swing.JButton consultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultado;
    // End of variables declaration//GEN-END:variables
}
