/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mantenimiento;

import javax.swing.JOptionPane;

/**
 *
 * @author miguel
 */

public class Llanta_prevencion extends javax.swing.JFrame {

    /**
     * Creates new form Llanta_prevencion
     */
    int intKilometrajeActual;//declaramos la variable donde se guardara el kilometraje que el usuario ingreso en le formulario anterior
    String StringMarca;//declaramos la variable donde se guardara la marca que el usuario ingreso en le formulario anterior
    int intModelo;//declaramos la variable donde se guardara el modelo que el usuario ingreso en le formulario anterior
    int intKilometrajeCambioDeLlantas;//en esta variable guardaremos el kilometraje del ultimo cambio que ingreso el usuario en este mismo formulario
    int intCambioLlanta;//se guarda la resta entre el kilometraje actual y el ultimo cambio para saber lo que se recorrio desde el ultimo cambio 
   
    public Llanta_prevencion() 
    {
        initComponents();
        this.setLocation(350,000);
    }
    
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cambiollantas = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        consulta_tipo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Cambio de llantas a manera de prevencion");

        cambiollantas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cambiollantasFocusLost(evt);
            }
        });

        aceptar.setText("aceptar");
        aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Ingrese el kilometraje en el que se realizo el ultimo ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("cambio de llantas seguido de  click en aceptar");

        resultado.setEditable(false);
        resultado.setBackground(new java.awt.Color(153, 204, 255));
        resultado.setColumns(20);
        resultado.setRows(5);
        jScrollPane2.setViewportView(resultado);

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\universidad\\semestre VI\\ingenieria de software\\Empresa M&D Software\\software\\java\\imagenes apra los formularios\\llantas completas.jpg")); // NOI18N
        jLabel5.setText("aca esta una imagen");

        consulta_tipo.setText("consultar nuevamente");
        consulta_tipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consulta_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta_tipoActionPerformed(evt);
            }
        });

        jLabel6.setText("Click en consultar nuevamente para realizar una nueva consulta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(consulta_tipo)
                        .addGap(146, 146, 146)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cambiollantas, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(339, 339, 339))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(aceptar)
                        .addGap(385, 385, 385))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3))
                            .addComponent(jLabel2))
                        .addGap(244, 244, 244))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cambiollantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(aceptar)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consulta_tipo)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //A continuacion crearemos los metodos cada uno con un argumento el cual nos permitira obtener el valor que el 
    //usuario ingreso en el formulario Automovil
   
    public void getinKilometrajeActual (int kilometraje)
    {
        intKilometrajeActual=kilometraje;
         
    }
    public void getmarca(String marca)
    {
       StringMarca=marca;
    }
    public void getmodelo(int modelo)
    {
       intModelo=modelo;
    }
    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
      
      intCambioLlanta= intKilometrajeActual-intKilometrajeCambioDeLlantas;//se resta el kilometraje actual menos el kilometraje en que se realizo el cambio de llantas y se guarda en al variable intCambioLlanta
      if((intCambioLlanta==40000)||(intCambioLlanta>40000))//se pone una condicion de comparar el kilometraje recorrido con el limite seguro cambiar una llanta para saber si se cumple o no la condicion
         {//si se cumple la codicion se imprimen los siguientes mensajes                                 
          resultado.setText("MARCA: "+StringMarca+"\n\n"+"MODELO:  "+intModelo+"\n\n"+"El vehiculo ha redorrido "+ intCambioLlanta+" kilometros desde\n el ultimo cambio.\n\nEs recomendable realizar un cambio de llantas\nen este momento, ya que se ha recorrido mas\nde 40000 kilometros");   
         }else//si no se cumple se imprimen los siguientes mensajes 
              {
              resultado.setText("MARCA:  "+StringMarca+"\n\n"+"MODELO:  "+intModelo+"\n\n"+"El vehiculo ha recorrido "+intCambioLlanta+" kilometros desde\nel ultimo cambio.\n\n"+"No es necesario realizar el cambio\nrecuerde que es recomendable cambiar llantas\ndespues de recorrer 40000 kilometros");
              }
    }//GEN-LAST:event_aceptarActionPerformed

    private void consulta_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta_tipoActionPerformed
           //en estem metodo retornaremos a el formulario tipovehiculo para realizar una nueva consulta
           setVisible(false);
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoVehiculo().setVisible(true);
            }
        });
    }//GEN-LAST:event_consulta_tipoActionPerformed

    private void cambiollantasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cambiollantasFocusLost
        //generamos nuevamente una excepcion para asegurarnos que en el campo sea ingresado solo enteros
      try{ 
          intKilometrajeCambioDeLlantas=Integer.parseInt(this.cambiollantas.getText());
         }catch(Exception a)
         {
         JOptionPane.showMessageDialog(this, Automovil.getmjsNumero());
         }        
    }//GEN-LAST:event_cambiollantasFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Llanta_prevencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Llanta_prevencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Llanta_prevencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Llanta_prevencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Llanta_prevencion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField cambiollantas;
    private javax.swing.JButton consulta_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea resultado;
    // End of variables declaration//GEN-END:variables
}
