/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mantenimiento;

import javax.swing.JOptionPane;

/**
 *
 * @author miguel
 */
public class Llanta_obligatorio extends javax.swing.JFrame {

    /**
     * Creates new form Llanta_obligatorio
     */
    //las siguientes variables guardaran enteros
    int intKilometrajeActual;
    int intKilometrajeCambioDeLlantas;
    int intCambioLlanta;
    int intModelo;
    String StringMarca;//esta variable guarda un string 
    public Llanta_obligatorio() {
        initComponents();
        this.setLocation(400,000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cambiollantas = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Conturtar_nuevamente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Cambio de llantas indispensable");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ingrese el kilometraje en el que se realizo el ultimo ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("cambio de llantas seguido de click en aceptar");

        cambiollantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiollantasActionPerformed(evt);
            }
        });
        cambiollantas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cambiollantasFocusLost(evt);
            }
        });

        aceptar.setText("aceptar");
        aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        resultado.setEditable(false);
        resultado.setBackground(new java.awt.Color(153, 204, 255));
        resultado.setColumns(20);
        resultado.setRows(5);
        jScrollPane1.setViewportView(resultado);

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\universidad\\semestre VI\\ingenieria de software\\Empresa M&D Software\\software\\java\\imagenes apra los formularios\\llantas completas.jpg")); // NOI18N
        jLabel4.setText("aca esta una imagen");

        jLabel5.setText("Click en consultar nuevamente para realizar una nueva consulta");

        Conturtar_nuevamente.setText("Consultar Nuevamente");
        Conturtar_nuevamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Conturtar_nuevamenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(cambiollantas, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(aceptar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel2)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel3)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Conturtar_nuevamente)
                        .addGap(198, 198, 198))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(cambiollantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(aceptar)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Conturtar_nuevamente))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        intCambioLlanta= intKilometrajeActual-intKilometrajeCambioDeLlantas;//se resta el kilometraje actual menos el kilometraje en que se realizo el cambio de llantas y se guarda en al variable intCambioLlanta
        if((intCambioLlanta==80000)||(intCambioLlanta>80000))//se pone una condicion de comparar el kilometraje recorrido con el limite seguro cambiar una llanta para saber si se cumple o no la condicion
         {//si se cumple la codicion se imprimen los siguientes mensajes                                 
          resultado.setText("\nMARCA: "+StringMarca+"\n\n"+"MODELO:  "+intModelo+"\n\n"+"su vehiculo ha redorrido "+ intCambioLlanta+" kilometros desde\n elultimo cambio.\n\nEs indispensable realizar un cambio de llantas\nen este momento, ya que se ha recorrido mas\nde 80000 kilometros");   
         }else//si no se cumple se imprimen los siguientes mensajes 
              {
              resultado.setText("\nMARCA:  "+StringMarca+"\n\n"+"MODELO:  "+intModelo+"\n\n"+"su vehiculo ha recorrido "+intCambioLlanta+" kilometros desde\nel ultimo cambio.\n\n"+"No es indispensable realizar el cambio en este\n momento recuerde que es indispensable cambiar llantas\ndespues de recorrer 80000 para evitar\nun accidente grave o mortal");
              }     
    }//GEN-LAST:event_aceptarActionPerformed

    private void Conturtar_nuevamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Conturtar_nuevamenteActionPerformed
        //en estem metodo retornaremos a el formulario tipovehiculo para realizar una nueva consulta
           setVisible(false);
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoVehiculo().setVisible(true);
            }
        });
    }//GEN-LAST:event_Conturtar_nuevamenteActionPerformed

    private void cambiollantasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cambiollantasFocusLost
      try{ 
          intKilometrajeCambioDeLlantas=Integer.parseInt(this.cambiollantas.getText());
         }catch(Exception e)
         {
         JOptionPane.showMessageDialog(this, Automovil.getmjsNumero());
         } 
    }//GEN-LAST:event_cambiollantasFocusLost

    private void cambiollantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiollantasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cambiollantasActionPerformed
    public void getinKilometrajeActual (int kilometraje)
    {
        intKilometrajeActual=kilometraje;
         
    }
    public void getmarca(String marca)
    {
       StringMarca=marca;
    }
    public void getmodelo(int modelo)
    {
       intModelo=modelo;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Llanta_obligatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Llanta_obligatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Llanta_obligatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Llanta_obligatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Llanta_obligatorio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Conturtar_nuevamente;
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField cambiollantas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultado;
    // End of variables declaration//GEN-END:variables
}
